### PR TITLE
Create Locky ransomware signature

### PR DESCRIPTION
**Pull request by kevross33**

### CODE REVIEW

**Comment by kevross33** [comment]
Ok, I will just ask as it will save me time, how from an API do I flag or check the process? I am going to see what other checks I can add in anyway but it is worth noting that I am not adding every HTTP request, just ones with main.php which is usually locky (currently unless more appear).

I might just look at a better way in the HTTP traffic to focus in with more conditions & hopefully checks

**Comment by kevross33** [comment]
Ok I have updated this to what I think is a working way of checking this (I depend on the previous match). It still worked in test but I am not sure if this is the best way or might result in false negatives or positives so would appreciate if you would cast your eye over it to check out these checks in the apis.

Also I added in a few extra registry keys

**Comment by spender-sandbox** [comment]
I think this sig won't work anymore -- the hardcoded reg key is gone in newer versions.

-Brad

**Comment by kevross33** [comment]
Yes you are right. It was a useful indicator at the time but I will need
to look into new more reliable indicators less prone to change although the
CnC emergingthreats sig work well for the classifcation for the moment.

**Comment by KillerInstinct** [comment]
I'll PR my locky sig on Monday.

**Pull request closed without merging**
