### PR TITLE
Add in signature to detect script timer

### PR DESCRIPTION
**Pull request by kevross33**
Use of script stopwatch stuff in script for potential evasion. Tested.

### CODE REVIEW

**Comment by kevross33** [comment]
image

**Comment by spender-sandbox** [comment]
This is a very un-optimized signature that's going to unnecessarily get called for every single window API over all arguments to perform its checks.  Also, do you have a link to a writeup or something about the technique this is targeting?

-Brad

**Comment by kevross33** [comment]
This signature is basically using the template of the anti-analysis tools signature for windows (i.e OLLYDBG window etc.). If you have any suggestions for performance improvements I will be happy to implement them.

You can also see this behaviour in this sample https://www.joesecurity.org/reports/report-cb25eb3053cc9b5dd6a3beedb04bb734.html for sample cb25eb3053cc9b5dd6a3beedb04bb734.

**Comment by spender-sandbox** [comment]
I thought I already added something to defeat that trick?

-Brad

**Comment by kevross33** [comment]
Not sure here what you mean. Are you meaning defeat the sleep evasion? If
so yes but this is to highlight its use.



On 10 Feb 2017 1:21 p.m., "Brad Spengler" <notifications@github.com> wrote:

I thought I already added something to defeat that trick?

-Brad

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spender-sandbox/community-modified/pull/241#issuecomment-278940477>,
or mute the thread

**Pull request merged**
