### PR TITLE
Update cuckoo files

### PR DESCRIPTION
**Pull request by kevross33**
No requirement to where agent.py/pyc actually located as you just have to put it inside VM and run.

### CODE REVIEW

**Comment by kevross33** [comment]
The analyzer one was interesting. seems it can be overwritten during ransomware analysis:

https://github.com/cuckoosandbox/cuckoo/issues/1029

**Comment by spender-sandbox** [comment]
That should only be an issue with the upstream cuckoo.

-Brad

**Comment by spender-sandbox** [comment]
Which is also why we don't really need these signature changes :)  The original checks were specifically for what was being used by Furtim.

-Brad

**Comment by kevross33** [comment]
Even if the issue doesn't exist isn't detection a good thing? The point
being to detect when someone is trying to detect even upstream
cuckoo/cuckoo 2.0? Some of these for instance are used in SEMs
https://github.com/AlicanAkyol/sems (always like these tools like pafish
too not just for sandbox evasion hardening but also making sure these
techniques can be detected).

**Comment by spender-sandbox** [comment]
The signature will simply never fire though -- because we hide the directories, the method they'd use to find the analyzer.py etc in the randomly-named dirs won't be able to find them, thus no entry in summary files, thus nothing for the signature to fire on.

-Brad

**Comment by kevross33** [comment]
Ah ok I understand now.

Thanks.

**Pull request closed without merging**
