### PR TITLE
Add signature to detect dropping ransom messages

### PR DESCRIPTION
**Pull request by kevross33**
First version of a signature to detect files writing likely ransomware messages to disk. Currently once I have it I just output the filename; the later intention is to extract the filename itself rather than the whole path but I was having difficulty getting it to work right. 

That would be preferable as ransomware messages typically are the same file dropped throughout the filesystem so just getting the file will take the list down from dozens to likely just one once it is working but I will look at sorting that up another time as this signature works for now and tried against a few ransomware families.

### CODE REVIEW

**Comment by spender-sandbox** [comment]
Should .lower() buff once instead of on every iteration of the loop

**Comment by spender-sandbox** [comment]
Also, why not just look through the first 4k of dropped files with certain file types?  Doing so many substring searches on every NtWriteFile would probably be much slower and more prone to false negatives (multiple single-byte writes, etc)

-Brad

**Comment by KillerInstinct** [comment]
Also, if you want to go the regex route, instead of iterating all the indicators, you should "|".join(indicators) and make it one big OR regex. Much more efficient that way.

**Comment by kevross33** [comment]
Hi,

Ok I have put in the .join and .lower() recommendations and tested against Satana ransomware. The other suggestion for the dropped file types and things recommendation I have a few questions/points on:

I am looking through NtWriteFile rather than dropped files because of bootkits writing ransomware messages (i.e Satana, Petya etc). These I don't think appear in dropped files. i.e with satana I get these results:

ransom_file: C:\Users\USER_NAME_REMOVED\AppData\Local\Temp!satana!.txt
ransom_file: \Device\Harddisk0\DR0

It could be possible I to look for extensions and types in the handle but I don't think that would be effecient and the list may result in false negatives. Only other in between compromise I can think of would be looking at NtWriteFile for bootkit style ransomware only with writes to disk and then mimetype on dropped files for everything else but obviously while improving performance I want to make it as generically useful as possible across current and future ransomware.

**Comment by spender-sandbox** [comment]
Would be best to split it into two cases then, otherwise it'll be buggy for the majority of ransomware.

-Brad

**Comment by kevross33** [comment]
satana

**Comment by kevross33** [comment]
Do you mean split it out in the way I suggested with dropped files and then bootkit stuff?

**Comment by spender-sandbox** [comment]
Yes, only do the NtWriteFile for pseudofiles that won't be dropped.

-Brad

**Comment by kevross33** [comment]
OK thanks; I will look to get that sorted out as that does sound like a good way to achieve this

**Comment by kevross33** [comment]
Ok done and tested. Now you get the filename on dropped files rather than the paths but that should be better given ransomware often drops the same file across the filesystem. Currnetly I only focus on "ACIII text" which covers my test ransomware currently (Telsacrypt and satana there) but I will likely need to expand to cover overs and avoid false negatives.

**Comment by KillerInstinct** [comment]
One other small nit-pick I'd suggest would be to only do a regex check if len(buff) >= 128 or something -- just to avoid some of the recent anti-analysis "api spamming" I've been seeing where people think it's funny to write a file 1 byte at a time. We don't want to run a regex  hundreds of times on 1 byte of data. :)

**Comment by kevross33** [comment]
ok done and tested. I tried moving the data check up a level to combine the mimetype & len check and the sig started throwing up an error on it so just added it as another check. The one for harddisk writing is fine too.

**Comment by kevross33** [comment]
I have been testing against various ransomware families & it has been working as hoped (actually better as I found it is getting HTML, VBS, Text, Bootkit writes etc). Here is Cerber:

cerber

**Pull request merged**
